"""Runs the chaos harness at a large trial count and writes docs/chaos-report.md.

Not part of the test suite - CI runs a few hundred trials as a normal test
(``test_outbox_chaos.py``); this is for generating the published numbers from a much
bigger sweep. Run it from the repo root:

    cd ephor && uv run python -m tests.generate_chaos_report

Override the trial count with EPHOR_CHAOS_TRIALS (default 50,000).
"""

from __future__ import annotations

import asyncio
import os
import time
from pathlib import Path

from tests.chaos_harness import CrashPoint, run_trials

DEFAULT_TRIALS = 50_000
REPORT_PATH = Path(__file__).resolve().parents[2] / "docs" / "chaos-report.md"


async def _main() -> None:
    trials = int(os.environ.get("EPHOR_CHAOS_TRIALS", DEFAULT_TRIALS))
    started = time.monotonic()
    summaries = await run_trials(trials)
    elapsed = time.monotonic() - started

    violations = [v for s in summaries for v in s.violations]
    total_jobs = sum(s.jobs for s in summaries)
    total_crashes = sum(s.crash_injections for s in summaries)

    by_point: dict[str, int] = {}
    for s in summaries:
        for point, count in s.crash_point_counts.items():
            by_point[point] = by_point.get(point, 0) + count

    point_rows = "\n".join(
        f"| `{point.value}` | {by_point.get(point.value, 0):,} |"
        for point in CrashPoint
    )
    headline = (
        "No violations across every trial."
        if not violations
        else ("Violations found - see below.")
    )

    report = f"""# Chaos report: exactly-once under randomised crash injection

Generated by `ephor/tests/generate_chaos_report.py` - a fuzzer that drives many jobs
through a real worker loop (`claim_batch` -> `start_attempt` -> the Adapter's call ->
the local commit -> `finish_attempt`), injecting a randomly chosen crash point on
every cycle, across many independently-seeded trials. See `chaos_harness.py`'s module
docstring for exactly what's checked and why; see ADR-0005 and ADR-0010 for the
guarantee itself. Regenerate this file by re-running the script - it isn't hand-edited.

## Result

| | |
| --- | --- |
| Trials | {trials:,} |
| Jobs simulated | {total_jobs:,} |
| Crash points injected | {total_crashes:,} |
| Violations found | **{len(violations)}** |
| Wall-clock time | {elapsed:.1f}s |

{headline}

## Crash points injected, by kind

| Crash point | Count |
| --- | --- |
{point_rows}

## What's actually checked, per job

- An idempotent Adapter never produces more than one real Effect, however many times
  it was crashed and retried.
- A job that finishes `SUCCEEDED` has exactly one real Effect behind it.
- A job that lands in `NEEDS_MANUAL_RECONCILIATION` has exactly one real Effect behind
  it, only ever for a non-idempotent Adapter.
- Every terminal job is asked about again with a real `claim_batch` call a year later
  in simulated time, and is never reclaimable.

## Violations

{"None." if not violations else chr(10).join(f"- {v}" for v in violations[:50])}
"""

    REPORT_PATH.write_text(report)
    print(f"wrote {REPORT_PATH} ({len(violations)} violations, {elapsed:.1f}s)")


if __name__ == "__main__":
    asyncio.run(_main())
